on:
  push:
    branches:
      - '!main'
    paths:
      - '**/*.svelte'
      - '**/*.ts'
      - '**/*.json'
      - '**/build-test.yml'
  pull_request: 
    paths:
      - '**/*.svelte'
      - '**/*.ts'
      - '**/*.json'
      - '**/build-test.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - run: bun run build

      - name: test with curl
        run: |
          bun run preview &
          sleep 5
          curl -v http://localhost:4173/ -I

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - run: bun run build

      - name: start server
        run: |
          bun run preview &
          sleep 5
      
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            http://localhost:4173/
            http://localhost:4173/en
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage