name: Intro to Github Action

on:
  push:
    branches: [ main, feature/actions]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo "Hello World"