name: Intro to Github Action

on:
  push:
    branches: [ main, feature/actions]
  pull_request:
    branches: [ main ]

jobs:
    build-test-pnpm:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v2.4.0
          with:
            version: latest
        - name: Install dependencies
          run: pnpm install
        - name: build
          run: pnpm run build
        - name: run the server
          run: |
            pnpm run preview & 
            sleep 5
        - name: Curl the server
          run: curl -I http://localhost:4173
        

           
        